name: Hello worlds
on: [ push ]
jobs:
  say-hello-inline-bash:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello worlds!"

  say-hello-action:
    runs-on: ubuntu-latest

    # Use the actions/hello-world-javascript-action action
    steps:
      # uses is a step type that allows you to use an action in your workflow
      - uses: actions/hello-world-javascript-action@v1
        with:
          who-to-greet: "work"
