name: Triggering github Events

# Events that trigger the workflows
on:
  # Trigger the workflow when a push is made to the branch
  push:
    branches:
      - example/expo-ci-cd-github-action

  # Trigger the workflow when a pull request is opened, synchronized, or reopened
  pull_request:
    # Trigger the workflow when a pull request is opened, synchronized, or reopened
    types:
      - opened
      - synchronize
      - reopened

    # Trigger the workflow when a file in the path is changed
    paths:
      - ".github/workflows/core-features-04-triggers-and-filters.yaml"

  # Trigger the workflow every day at midnight
  schedule:
    - cron: "0 0 * * *" # every day at midnight

  # Trigger the workflow when a workflow_dispatch event is triggered
  workflow_dispatch:

jobs:
  # Job to run the workflow
  run-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: "Dump full event JSON"
        run: |
          echo "=============== $GITHUB_EVENT_PATH payload ==============="
          cat "$GITHUB_EVENT_PATH"
